{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: 成功了\nassert 'hello' == 'hi'\n  - hello\n  + hi", "trace": "self = <Cases.test.Test_Class object at 0x0000022EA44F8748>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert x == \"hi\", '成功了'\nE       AssertionError: 成功了\nE       assert 'hello' == 'hi'\nE         - hello\nE         + hi\n\nCases\\test.py:14: AssertionError"}, "start": 1573200027363, "stop": 1573200027364, "uuid": "6faba896-51ae-4c9c-a534-fad72e208506", "historyId": "67156529111d7481d1d9e8c025b007d6", "testCaseId": "9130bd84b644a28945ff3d522c5903ba", "fullName": "Cases.test.Test_Class#test_two", "labels": [{"name": "parentSuite", "value": "Cases"}, {"name": "suite", "value": "test"}, {"name": "subSuite", "value": "Test_Class"}, {"name": "host", "value": "DESKTOP-GN7855I"}, {"name": "thread", "value": "15720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Cases.test"}]}